# Change these first
owner: kpocius # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: SearXNG
    url: https://s.poci.us/healthz
    type: globalping
    location: Lithuania
  - name: GoToSocial
    url: https://gts.poci.us/about
    type: globalping
    location: Lithuania
  - name: The Lounge
    url: https://irc.poci.us
    type: globalping
    location: Lithuania
  - name: The Lounge (Public)
    url: https://lounge.poci.us
    type: globalping
    location: Lithuania
  - name: Matrix
    url: https://matrix.poci.us
    icon: https://matrix.org/assets/favicon.ico
    type: globalping
    location: Lithuania
  - name: Caddy
    url: https://poci.us/healthz
    icon: https://caddyserver.com/resources/images/favicon.png
    type: globalping
    location: Lithuania

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.poci.us
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
