owner: kpocius
repo: uptime

sites:
  - name: Caddy
    url: https://poci.us/healthz
    icon: https://caddyserver.com/resources/images/favicon.png
    type: globalping
    location: Lithuania
  - name: SearXNG
    url: https://s.poci.us/healthz
    type: globalping
    location: Lithuania
  - name: GoToSocial
    url: https://gts.poci.us/api/v2/instance
    type: globalping
    location: Lithuania
  - name: The Lounge
    url: https://irc.poci.us
    type: globalping
    location: Lithuania
  - name: The Lounge Public
    url: https://lounge.poci.us
    type: globalping
    location: Lithuania
  - name: Matrix
    url: https://matrix.poci.us
    icon: https://matrix.org/assets/favicon.ico
    type: globalping
    location: Lithuania
  - name: Caddy Proxy
    url: https://poci.us/feed/vilnius
    icon: https://caddyserver.com/resources/images/favicon.png
    type: globalping
    location: London
  - name: Globalping
    url: https://globalping.io/
    type: globalping
    location: kpocius

status-website:
  cname: status.poci.us
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Poci.us & Co.
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
